### ISSUE TITLE
set-env being deprecated

### ISSUE THREAD

**Issue by abatilo** [asdf-vm/actions#122]
[Here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) is the GH Action notice/announcement.

[Here](https://github.com/asdf-vm/actions/blob/master/setup/main.js#L207) is an example of where `set-env` is being used.

>Action authors who are using the toolkit should update the @actions/core package to v1.2.6 or greater to get the updated addPath and exportVariable functions.

The `@actions/core` package just needs to be updated.

**Comment by abatilo** [comment]
Closing. This repo is using the correct version. It was another action in my workflow that was causing the warning.

**Comment by abatilo** [comment]
Wait, re-opening. HEAD has the updated version but the action itself has not been published since the update.

**Comment by smorimoto** [comment]
Released.

**Comment by smorimoto** [comment]
And the v1 tag is moved to v1.0.1.
