### ISSUE TITLE
The `set-env` command is deprecated. Please upgrade to using Environment Files.

### ISSUE THREAD

**Issue by AZMCode** [asdf-vm/actions#175]

**Comment by smorimoto** [comment]
Use latest version instead (v1).

**Comment by AZMCode** [comment]
I have tried it with v1.0.1, got this. Not sure if anything is going wrong on my side. I'll keep an eye out. Thanks for your time!

**Comment by smorimoto** [comment]
You seem to be hitting the rate limit now. Why did you stop giving tokens? It’s necessary to get the latest version on CI.

**Comment by AZMCode** [comment]
I'm sorry, are you referring to the repo i'm working on now?

**Comment by smorimoto** [comment]
No need to apologize :) Yes.

**Comment by AZMCode** [comment]
That might be better discussed in its own issue. For now, thanks for the help.
