### ISSUE TITLE
.asdfrc not respected

### ISSUE THREAD

**Issue by yhakbar** [asdf-vm/actions#240]
Hello!

I was really excited to see this GitHub Action available, as it could significantly reduce the configuration required to get actions running, but I've run into an issue with using it for nodejs installs.

As you can see in [this run](https://github.com/yhakbar/asdf-gha-test/runs/1935584177?check_suite_focus=true), with [these configs](https://github.com/yhakbar/asdf-gha-test/tree/26113c7e716231abc61b95732b9254d369576458), the action is ignoring `.asdfrc` which would allow us to leverage the `legacy_version_file = yes` configuration and read the nodejs version from `.nvmrc`.

The project I'm working on has users that would prefer not to force all the developers to switch over to asdf, so the ability to support this would be much appreciated.

**Comment by afirth** [comment]
I guess you just need to copy .asdfrc to $HOME. 
https://github.com/asdf-vm/asdf/issues/41

**Comment by yhakbar** [comment]
Sorry, I forgot about this issue. I imagine your suggestion is correct. I'll create a new issue if I find that it wasn't.
