### ISSUE TITLE
yarn build fails

### ISSUE THREAD

**Issue by afirth** [asdf-vm/actions#325]
probably just me (tsc noob), but perhaps worth documenting how to build this repo to encourage contributions
I had to:
``` bash
npm i @actions/exec
npm i @actions/core
npm i @actions/io
npm i @actions/github
yarn build
```
`yarn add` or `yarn install` was not sufficient to get the bundles to build, and without the npm calls I get a bunch of errors on
```bash
yarn build
[...]
 > lib/plugins-add/index.ts: error: Could not resolve "@actions/core" (mark it as external to exclude it from the bundle)
    1 │ import * as core from "@actions/core";
      ╵                       ~~~~~~~~~~~~~~~
```

**Comment by jthegedus** [comment]
Please reopen if still an issue
