### ISSUE TITLE
Actions fails to install nodejs lts version 

### ISSUE THREAD

**Issue by snowe2010** [asdf-vm/actions#466]
The action fails to install nodejs lts version. I'm not sure if this is just an issue with custom builder, but even if you ssh into the build server, source asdf, install the lts version, then rebuild from github, it still fails with the message:

```
Cloning node-build...
node-build: definition not found: lts
Error: Action failed with error Error: The process '/home/runner/.asdf/bin/asdf' failed with exit code 1
```

This does not appear to be a problem with asdf or the nodejs plugin, as it works to install both locally and manually on the server. It _only_ fails through the action.

**Comment by afirth** [comment]
This happens because the action version is out of date. I think the support was introduced in ~v0.10.0
maybe @smorimoto can release a new version?

**Comment by jthegedus** [comment]
Please test with this version: https://github.com/asdf-vm/actions/releases/tag/v2.0.0

Currently only supports full semver version referencing:

```
uses: asdf-vm/actions/install@v2.0.0
```

**Comment by jthegedus** [comment]
Reopen if issue persists

**Comment by snowe2010** [comment]
Awesome. Thank you. I've actually been using `master` for a while due to other issues, but it seems like v2 will have everything I need. thanks!
