### ISSUE TITLE
Upgrade to Node.js 16

### ISSUE THREAD

**Issue by Kurt-von-Laven** [asdf-vm/actions#484]
This repository uses Node.js 12 actions, which are deprecated. GitHub Actions recently began adding the following annotation warning all users of asdf-vm/actions:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: asdf-vm/actions

**Comment by jthegedus** [comment]
Hi all, sorry for the delay here. We have merged the PR #488 which resolved these issues.

As far as releasing this specific change goes, I want to re-jig the GitHub Releases to follow the automation we have in our other repos, so until a tagged version becomes available, I will ask you all to use the commit reference style:

```
  # Reference a specific commit (most strict)
  - uses: asdf-vm/actions/plugin-test@a368498
```

Where the SHA is the commit from master after the merge

**Comment by Kurt-von-Laven** [comment]
@jthegedus, it might be worth either creating issue(s) for the changes to the release process so that others can help if they are able or manually releasing this change. GitHub announced their intention to [migrate Node.js 12 actions to Node.js 16 around June-August 2023](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/), which could potentially be needlessly disruptive if all doesn't go smoothly for everyone.

**Comment by jthegedus** [comment]
@Kurt-von-Laven As part of my upcoming updates to this repo the release process will follow the same as the core asdf repo so any core member can release with a simple PR merge. Updating this repo is top of my priority list, so when I get a chance in the coming weeks this will be addressed.

**Comment by Kurt-von-Laven** [comment]
Thank you! It's greatly appreciated.
