### ISSUE TITLE
Are these actions no longer released?

### ISSUE THREAD

**Issue by mickamy** [asdf-vm/actions#503]
It seems like there have been no releases since 2020 as I see git tags in this repo.
Are these actions no longer released?

<img width="545" alt="Screen Shot 2022-12-25 at 12 19 19" src="https://user-images.githubusercontent.com/11856337/209455992-2afb8825-af7c-4c2b-a4ee-f360c5fd2dd4.png">

**Comment by mickamy** [comment]
I use commit hash to get latest version of it. But simpler notation (like v1) would be nice.
Thanks for the great product btw.

**Comment by jthegedus** [comment]
I will be stewarding this particular repo within the asdf core team. I am on holidays at this time but will be reworking and releasing `2.0` version of this in the new year (2023). Thanks for your patience.

**Comment by mickamy** [comment]
Thank you so much!

**Comment by mickamy** [comment]
@jthegedus 
Seems like no releases are not out yet.
Would you please take a look for this?

**Comment by jthegedus** [comment]
Please be patient. I have yet to have a day at the computer to write code this year. I will address this before almost anything else when I get the time. It is a high priority for me.

**Comment by mickamy** [comment]
@jthegedus 
I am so sorry to bother you but I gotta ask you. Not yet?
If there were any thing that I can help you, I am happy to do that.

Thanks,

**Comment by jthegedus** [comment]
https://github.com/asdf-vm/actions/releases/tag/v2.0.0

Please test and report issues!

**Comment by mickamy** [comment]
Thank you so much!
I'll use it and report an issue once I found.

Thanks again!
