### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by pacoguzman** [asdf-vm/actions#510]
Is it possible to have a new major version release of the actions?

I understand you're following semver, and there are no relevant changes to bump the action versions. But we would like to get rid of [deprecation warnings](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)  with changes already done in this [commit](6844d09b13209e7d2ce3b63d2b089a2acef581ec)

Thanks in advance

**Comment by jthegedus** [comment]
https://github.com/asdf-vm/actions/issues/484#issuecomment-1376772513

**Comment by jthegedus** [comment]
https://github.com/asdf-vm/actions/releases/tag/v2.0.0

Currently only supports full semver version:

```
uses: asdf-vm/actions/install@v2.0.0
```

Please test and report issues!
