### ISSUE TITLE
Update Node.js

### ISSUE THREAD

**Issue by ai** [asdf-vm/actions#538]
Right now Github Actions warns about old Node.js in this action:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: asdf-vm/actions/setup@v1
```

I recommend switching to Node.js 18.

**Comment by jthegedus** [comment]
This was resolved in the recent `v2` release. As you can see with the code here:

https://github.com/asdf-vm/actions/blob/75bab86b342b8aa14f3b547296607599522cbe90/setup/action.yml#L5

GitHub Actions do not yet support `node18`, so we are on the latest `node16`

**Comment by ericcornelissen** [comment]
@jthegedus, since you mentioned `node18` here I wanted to flag that `node20` can now be used by Actions now - see for example [`actions/checkout`](https://github.com/actions/checkout/blob/72f2cec99f417b1a1c5e2e88945068983b7965f9/action.yml#L93).

**Comment by jthegedus** [comment]
> @jthegedus, since you mentioned `node18` here I wanted to flag that `node20` can now be used by Actions now - see for example [`actions/checkout`](https://github.com/actions/checkout/blob/72f2cec99f417b1a1c5e2e88945068983b7965f9/action.yml#L93). Like `node14`, I believe GitHub decided to skip `node18`.

`node20` merged in https://github.com/asdf-vm/actions/pull/558 and immediately usable with:

```diff
-  - uses: asdf-vm/actions/setup@v2
+  - uses: asdf-vm/actions/setup@a2d44a7
```

We will let people test this first before merging in the near future.
