### ISSUE TITLE
Using plugin-test with asdf-jq

### ISSUE THREAD

**Issue by AZMCode** [asdf-vm/actions#63]
It seems the action plugin-test that asdf-jq uses to test its builds already has jq installed by default, leading to [erroneous passing tests](https://github.com/focused-labs/asdf-jq/issues/3)

**Comment by imbsky** [comment]
This is probably not a problem with this action, but with the plugin-test in asdf. A quick workaround is to remove jq from actions vm before testing. But, I think it would be ideal for asdf to understand its setup and test within it.

**Comment by imbsky** [comment]
https://github.com/asdf-vm/actions/blob/master/lib/plugin-test/index.ts#L20-L29

**Comment by AZMCode** [comment]
> But, I think it would be ideal for asdf to understand its setup and test within it.

Absolutely, because asdf-java requires jq to work, and just removing jq would cause their tests to fail.

**Comment by AZMCode** [comment]
> This is probably not a problem with this action, but with the plugin-test in asdf.

Should I move this issue?

**Comment by imbsky** [comment]
Yeah, that would be useful.

**Comment by imbsky** [comment]
Wait, it doesn't seem to get the correct version for some reason.

```
jq  is already installed
jq-1.5-1-a5b5cbe
```

is not correct.

```
jq 1.6 is already installed
```

is correct.
